### PR TITLE
Cope with error codes sometimes added to the chcp output

### PR DESCRIPTION
**Pull request by xavier-deryckere**

### CODE REVIEW

**Comment by tomas** [comment]
Great. Any chances you could add a test to make sure we don't break anything unexpectedly?

**Comment by xavier-deryckere** [comment]
> Great. Any chances you could add a test to make sure we don't break anything unexpectedly?

You mean a basic test to validate the code on a few output samples, Just plain javascript with no direct link with wmic?
Or test the startup of the library with a moq to simulate chcp outputs (which is a very different story)?

**Comment by tomas** [comment]
Just a simple test to verify a few scenarios with different console encodings and see if it works as expected. Nothing too fancy.

**Comment by xavier-deryckere** [comment]
Done!

**Comment by tomas** [comment]
Cool. Any chance you can call the actual function from index.js instead of having a second copy of it in the test?

**Comment by xavier-deryckere** [comment]
ok I made a function so the unit test calls actual code.

**Comment by tomas** [comment]
Beautiful, thanks

**Comment by tomas** [comment]
Ok just pushed v1.0.0 with this merged along with other PRs.

**Pull request merged**
