### PR TITLE
Parse multiple lines

### PR DESCRIPTION
**Pull request by Arcath**
This fixes the issue in #1 where `get_values()` returns a single reply instead of all of them.

```
wmic.get_values('logicaldisk', 'name, volumename', null, function(err, values) {
  console.log(err || values);
});
```

now returns

```
 [ { Name: 'C:', VolumeName: 'Windows' },
   { Name: 'L:' },
   { Name: 'R:' },
   { Name: 'S:' },
   { Name: 'T:' },
   { Name: 'U:' },
   { Name: 'V:' },
   { Name: 'W:' } ] }
```

### CODE REVIEW

**Comment by tomas** [comment]
Very nice, sir. Would you mind adding a (simple) test case so we don't break this in the future? I usually test with the mocha/should combination, using sinon for spies and stubs.

**Comment by Arcath** [comment]
Will look at adding a test shortly

**Comment by Arcath** [comment]
That should be all sorted, its working very well off this fork in my current project.

**Comment by tomas** [comment]
Very nice sir. I'll take a look when I have a minute!

**Comment by tomas** [comment]
After a very long time this has finally landed on 882a661f225377b1d8f221c08604a2deb2138243.

Thanks again!

**Pull request closed without merging**
